C# 异常处理 异常是在程序执行期间出现的问题。C# 中的异常是对程序运行时出现的特殊情况的一种响应，比如尝试除以零。

异常提供了一种把程序控制权从某个部分转移到另一个部分的方式。C# 异常处理时建立在四个关键词之上的：try、catch、finally 和 throw。

try：一个 try 块标识了一个将被激活的特定的异常的代码块。后跟一个或多个 catch 块。 catch：程序通过异常处理程序捕获异常。catch 关键字表示异常的捕获。 finally：finally 块用于执行给定的语句，不管异常是否被抛出都会执行。例如，如果您打开一个文件，不管是否出现异常文件都要被关闭。 throw：当问题出现时，程序抛出一个异常。使用 throw 关键字来完成。 try { // 引起异常的语句 } catch( ExceptionName e1 ) { // 错误处理代码 } catch( ExceptionName e2 ) { // 错误处理代码 } catch( ExceptionName eN ) { // 错误处理代码 } finally { // 要执行的语句 }

C# 中的异常类 System.IO.IOException 处理 I/O 错误。 System.IndexOutOfRangeException 处理当方法指向超出范围的数组索引时生成的错误。 System.ArrayTypeMismatchException 处理当数组类型不匹配时生成的错误。 System.NullReferenceException 处理当依从一个空对象时生成的错误。 System.DivideByZeroException 处理当除以零时生成的错误。 System.InvalidCastException 处理在类型转换期间生成的错误。 System.OutOfMemoryException 处理空闲内存不足生成的错误。 System.StackOverflowException 处理栈溢出生成的错误。